---

- name: Check network device OS
  assert:
    that: >
      ansible_network_os == 'nxos' or
      ansible_network_os == 'ios'
    msg: "Network device OS not defined or not supported by this role: {{ ansible_network_os }}"

- name: Configure link aggregation on interfaces 
  nxos_linkagg:
    group: "{{ item.value.name | regex_replace('port-channel') }}"    
    mode: "{{ item.value.linkagg.mode | default(omit) }}"
    members: "{{ item.value.linkagg.member_of_po | default(omit) }}"
    force: "{{ item.value.linkagg.force | default(omit) }}"
    min_links: "{{ item.value.linkagg.min_links | default(omit) }}"
  with_dict: "{{ interfaces }}"
  when: >
    ansible_network_os == 'nxos' and
    item.value.linkagg is defined
  tags: 
    - mlag_config
    - nxos 

- name: Configure vPC on interfaces 
  nxos_vpc_interface: 
    portchannel: "{{ item.value.name | regex_replace('port-channel') }}"
    state: "{{ item.value.vpc.state | default('present') }}"
    vpc: "{{ item.value.vpc.id | default( item.value.name | regex_replace('port-channel') ) }}"    
  with_dict: "{{ interfaces }}"
  when: >
    ansible_network_os == 'nxos' and    
    item.value.vpc is defined
  tags: 
    - mlag_config
    - nxos
